### ISSUE TITLE
First-order vs separable

### ISSUE THREAD

**Issue by neldredge-unco** [twjudson/odeproject-public#4]
https://github.com/twjudson/odeproject-public/blob/0cb06bbf9c67d967a33d9b54b18ca42a7f654f34/source/firstlook05.ptx#L24-L26

As far as I can see, such an equation typically isn't separable even if `p(t)` *is* a constant.  For instance, `dx/dt + x = t` isn't separable.  I guess it would be separable if `q(t) = c p(t)` for some constant c (maybe that is necessary?)

**Comment by twjudson** [comment]
Hi Nate,

I corrected this.  The best course of action if you find more errors is to make an issue on GitHub.

Cheers,
Tom

On Sep 29, 2023, at 12:22 AM, Nate Eldredge ***@***.***> wrote:


This Message Is From an External Sender
This message came from outside your organization.


https://github.com/twjudson/odeproject-public/blob/0cb06bbf9c67d967a33d9b54b18ca42a7f654f34/source/firstlook05.ptx#L24-L26<https://urldefense.com/v3/__https://github.com/twjudson/odeproject-public/blob/0cb06bbf9c67d967a33d9b54b18ca42a7f654f34/source/firstlook05.ptx*L24-L26__;Iw!!FvPYdGY!fTOpjdeIdFzQTlke9yMgeXnqIsg0lKHJcGfNMwJSXSVOVYxMFYEemgPre5rgq3Nj-645WySDLCPir1JIvWSwmCh8yQ$>

As far as I can see, such an equation typically isn't separable even if p(t) is a constant. For instance, dx/dt + x = t isn't separable. I guess it would be separable if q(t) = c p(t) for some constant c (maybe that is necessary?)
